title: Radu Epure
description: My Personal Blog
author: Radu Epure
logo: /static/img/avatar.png
github: https://github.com/the-wabbit
about: DevOps

baseurl: "/"
url: "blog.the-wabb.it"

allowsearch: false

disqus_shortname: the-wabb-it
google_analytics: UA-122941221-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
